kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.name  }}-service"
  labels:
    app: "{{ .Values.name  }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - name: jrf-jmx
      port: 10250
      targetPort: 10250
      protocol: TCP
  selector:
   app: "{{ .Values.name  }}"
